### ISSUE TITLE
Calculating the X business days from a given day

### ISSUE THREAD

**Issue by tomaszhanc** [aeon-php/business-hours#72]
Hi,

I asked on the forum about it, but because of no answer I decided to ask about it also here.

**Describe the feature**
I would like to have a method in the library which would be able to calculate the date by adding eg: 5 business days to passed day. I noticed that I have to duplicate that part of code when needed in different contexts/applications, but I think that the library could do something like that.

**Expected behavior**
Probably the code would be the best explanation of the behavior:

```php
public function nextBusinessDays(Day $day, int $businessDays, int $maximumDays = 365) : Day
{
    $nextBusinessDay = $day;

    for ($i = 1; $i <= $businessDays; $i++) {
        $nextBusinessDay = $this->nextBusinessDay($nextBusinessDay, $maximumDays);
    }

    return $nextBusinessDay;
}
```

I’ll need to find a better name for that method. Let me know, what do you think about it.

**Comment by norberttech** [comment]
Yeah, sorry for the forum, it didn’t work as I expected :( I’m going to migrate to github discussions that are much harder to miss. 
About your question, I’m not sure if I fully understand the use case, you want to find iterate over business days (skipping non business days) until you reach that passed number of business days?

**Comment by tomaszhanc** [comment]
Yes, exactly. For example, I need to add 5 business days to today's date:

**business days:** from Monday to Friday
**custom non-business day:** 2021-08-24, Tuesday
**today:** 2021-08-19, Thursday

+1 day: 2021-08-20, Friday, working day, total added: **1 day**
+1 day: 2021-08-21, Saturday, non-working day, total added: 1 day
+1 day: 2021-08-22, Sunday, non-working day, total added: 1 day
+1 day: 2021-08-23, Monday, working day, total added: **2 days**
+1 day: 2021-08-24, Tuesday, (custom) non-working day, total added: 2 days
+1 day: 2021-08-25, Wednesday, working day, total added: **3 days**
+1 day: 2021-08-26, Thursday, working day, total added: **4 days**
+1 day: 2021-08-27, Friday, working day, total added: **5 days**

Is it generic enough behavior to add it as a part of the library?

**Comment by norberttech** [comment]
yep, sounds good to me 👍
